apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-app
  namespace: zabbix_monitoring

data:
  MYSQL_DATABASE: zabbix
  MYSQL_USER: zabbix
  ZBX_ENABLE_SNMP_TRAPS: "true"
  ZBX_JAVAGATEWAY_ENABLE: "true"
  ZBX_STARTJAVAPOLLERS: "5"
  ZBX_SERVER_NAME: zabbix_server_K8s
  ZBX_SERVER_HOST: "zabbix_server_host"
  ZBX_SERVER_PORT: "10051"
  DB_SERVER_HOST: "zabbix_mysql_server_host"
  PHP_TZ: "Europe/Paris"
  ZBX_HOSTNAME: "zabbix_server"
  ZBX_DEBUGLEVEL: "4"
